---
- hosts: localhost
  connection: local
  tasks:
    - include_vars: "../stackhead-repo/ansible/__tests__/variables.yml"
    - block:
        - debug:
            msg: "Run your tests here by importing the respective tasks"
        #- name: Generate Server Block Terraform file
        #  import_tasks: "../tasks/steps/generate-serverblock-tf.yml"
      vars:
        role_path: ".."
